serviceMaps:
  serviceName: egov-filemgmnt
  mappings:
  - version: 1.0
    description: Persists applicant details in egov_filemgmnt database, eg_fm_applicantpersonal table
    fromTopic: save-fm-applicantpersonal
    isTransaction: true
    queryMaps:
    - query: >
        INSERT INTO eg_fm_applicantpersonal(id, aadhaarno, email, firstname, lastname, title, mobileno, tenantid, fatherfirstname, fatherlastname, motherfirstname, motherlastname, applicantcategory, dateofbirth, bankaccountno, createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      basePath: ApplicantPersonals.*
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.id

      - jsonPath: $.ApplicantPersonals.*.aadhaarNo 
      
      - jsonPath: $.ApplicantPersonals.*.email 
      
      - jsonPath: $.ApplicantPersonals.*.firstName 
      
      - jsonPath: $.ApplicantPersonals.*.lastName 
      
      - jsonPath: $.ApplicantPersonals.*.title 
      
      - jsonPath: $.ApplicantPersonals.*.mobileNo 
      
      - jsonPath: $.ApplicantPersonals.*.tenantId
      
      - jsonPath: $.ApplicantPersonals.*.fatherFirstName
      
      - jsonPath: $.ApplicantPersonals.*.fatherLastName
      
      - jsonPath: $.ApplicantPersonals.*.motherFirstName
      
      - jsonPath: $.ApplicantPersonals.*.motherLastName
      
      - jsonPath: $.ApplicantPersonals.*.applicantCategory
      
      - jsonPath: $.ApplicantPersonals.*.dateOfBirth
      
      - jsonPath: $.ApplicantPersonals.*.bankAccountNo
      
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
      
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime
      
    - query: >
        INSERT INTO eg_fm_servicedetail(id, applicantpersonalid, serviceid, servicecode, businessservice, workflowcode, createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      basePath: ApplicantPersonals.*.serviceDetails
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.id

      - jsonPath: $.ApplicantPersonals.*.id
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.serviceId 
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.serviceCode 
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.businessService 
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.workflowCode 
      
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
      
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime      
 
      
    - query: >
        INSERT INTO eg_fm_applicantaddress(id, houseno, housename, street, pincode, postofficename, residenceassociationno, localplace, mainplace, wardno, createdby, createddate, lastmodifiedby, lastmodifieddate,applicantpersonalid)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
      basePath: ApplicantPersonals.*.applicantAddresses
      jsonMaps:    
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.id

      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.houseNo
     
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.houseName
     
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.street
     
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.pincode
     
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.postOfficeName
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.residenceAssociationNo
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.localPlace
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.mainPlace
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.wardNo
     
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
     
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime  
 
      - jsonPath: $.ApplicantPersonals.*.id
      
    - query: >
        INSERT INTO eg_fm_applicantdocument(id, applicantpersonalid, documenttypeid, documentnumber, docexpirydate, createdby, createddate, lastmodifiedby, lastmodifieddate )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?  )        
      basePath: ApplicantPersonals.*.applicantDocuments
      jsonMaps:    
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.id         
      
      - jsonPath: $.ApplicantPersonals.*.id
      
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.documenttypeId

      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.documentNumber
     
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.docexpiryDate              
       
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
     
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime  
      
    - query: >
        INSERT INTO eg_fm_applicantservicedocument(id, applicantid, servicedetailsid, documenttypeid, filestoreid, active, documentnumber, applicationdetails, createdby, createddate, lastmodifiedby, lastmodifieddate)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )        
      basePath: ApplicantPersonals.*.applicantServiceDocuments
      jsonMaps:    
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.id         
      
      - jsonPath: $.ApplicantPersonals.*.id
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.id

      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.documentTypeId
     
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.fileStoreId
     
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.active 
      
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.documentNumber 
       
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.applicationDetails              
       
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
     
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime 
      
     
      
    - query: >
        INSERT INTO eg_fm_filedetail(id, tenantid, servicedetailsid, filenumber, filecode, filename, filearisingmode, filearisingdate, financialyear, applicationdate, workflowcode, action, filestatus, createdby, createddate, lastmodifiedby, lastmodifieddate)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?, ?, ? )        
      basePath: ApplicantPersonals.*.fileDetail
      jsonMaps:    
      - jsonPath: $.ApplicantPersonals.*.fileDetail.id         
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.tenantId
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.id

      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileNumber
     
      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileCode
     
      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileName     
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileArisingMode 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileArisingDate 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.financialYear 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.applicationDate 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.workflowCode 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.action 
      
      - jsonPath: $.ApplicantPersonals.*.fileDetail.fileStatus          
       
      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.createdTime
     
      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedBy

      - jsonPath: $.ApplicantPersonals.*.auditDetails.lastModifiedTime          

  - version: 1.0
    description: Update applicant details in egov_filemgmnt database, eg_fm_applicantpersonal table
    fromTopic: update-fm-applicantpersonal
    isTransaction: true
    queryMaps:
    - query: >
        UPDATE eg_fm_applicantpersonal 
        SET aadhaarno = ?, email = ?, firstname = ?, lastname = ?, title = ?, mobileno = ?
        WHERE id = ?;
      basePath: ApplicantPersonals.*
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.aadhaarNo 
      
      - jsonPath: $.ApplicantPersonals.*.email 
      
      - jsonPath: $.ApplicantPersonals.*.firstName 
      
      - jsonPath: $.ApplicantPersonals.*.lastName 
      
      - jsonPath: $.ApplicantPersonals.*.title 
      
      - jsonPath: $.ApplicantPersonals.*.mobileNo       
         
      - jsonPath: $.ApplicantPersonals.*.id        
      
    - query: >      
        UPDATE eg_fm_applicantaddress 
        SET houseno = ?, housename = ?, street = ?, pincode = ?, postofficename = ?
        WHERE applicantpersonalid = ?;
      basePath: ApplicantPersonals.*.applicantAddresses
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.houseNo 
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.houseName  
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.street 
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.pincode
      
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.postOfficeName          
         
      - jsonPath: $.ApplicantPersonals.*.applicantAddresses.applicantpersonalid
      
    - query: >      
        UPDATE eg_fm_applicantdocument 
        SET documenttypeid = ?, documentnumber = ?, docexpirydate = ?        
        WHERE applicantpersonalid = ?;
      basePath: ApplicantPersonals.*.applicantDocuments
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.documenttypeId 
      
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.documentNumber  
      
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.docexpiryDate             
         
      - jsonPath: $.ApplicantPersonals.*.applicantDocuments.applicantpersonalid 
      
    - query: >      
        UPDATE eg_fm_applicantservicedocument
        SET documenttypeid = ?, servicedetailsid = ?     
        WHERE applicantid = ?;
      basePath: ApplicantPersonals.*.applicantServiceDocuments
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.serviceDetailsId 
      
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.documentTypeId             
         
      - jsonPath: $.ApplicantPersonals.*.applicantServiceDocuments.applicantid  
      
    - query: >      
        UPDATE eg_fm_servicedetail
        SET servicecode = ?, businessservice = ?, workflowcode = ?        
        WHERE applicantpersonalid = ?;
      basePath: ApplicantPersonals.*.serviceDetails
      jsonMaps:
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.serviceCode 
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.businessService  
      
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.workflowCode             
         
      - jsonPath: $.ApplicantPersonals.*.serviceDetails.applicantpersonalid 
            
            
  - version: 1.0
    description: Persists communication file  details in egov_filemgmnt database, eg_fm_communicationfile table
    fromTopic: save-fm-communicationfile
    isTransaction: true
    queryMaps:
    - query: >
        INSERT INTO eg_fm_communicationfile(id, subjecttypeid, senderid, priorityid, filestoreid, details, createdby, createddate, lastmodifiedby, lastmodifieddate) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      basePath: CommunicationFile.*
      jsonMaps:
      - jsonPath: $.CommunicationFile.*.id

      - jsonPath: $.CommunicationFile.*.subjectTypeId 
      
      - jsonPath: $.CommunicationFile.*.senderId 
      
      - jsonPath: $.CommunicationFile.*.priorityId 
      
      - jsonPath: $.CommunicationFile.*.fileStoreId 
      
      - jsonPath: $.CommunicationFile.*.details 
      
      - jsonPath: $.CommunicationFile.*.auditDetails.createdBy

      - jsonPath: $.CommunicationFile.*.auditDetails.createdTime
      
      - jsonPath: $.CommunicationFile.*.auditDetails.lastModifiedBy

      - jsonPath: $.CommunicationFile.*.auditDetails.lastModifiedTime
